### PR TITLE
Website redesign + add authors page

### PR DESCRIPTION
**Pull request by ezrichards**
I haven't finished styling yet, but I put some basic information in there & all of the necessary contact information. Let me know what you think!

### CODE REVIEW

**Review by sumnerevans — COMMENTED** [review]
The old mines.png is the same one that is being used on https://mines.edu, so we should not change it

**Comment by ezrichards** [comment]
> The old mines.png is the same one that is being used on https://mines.edu, so we should not change it

Unfortunately, this isn't an option. I spoke with the Mines Brand Manager and received approval [to use the Mines logo](https://www.mines.edu/webcentral/logos/), but they asked that we use the new one. I want to be careful and respectful of brand representation.

When we have a final "draft" of the site ready, I'll send it back and ensure that the logo is being used under the correct guidelines. I recall that there was a Mines survey about a potential logo change last semester so this might not matter anyways.

**Comment by sumnerevans** [comment]
Are you sure? The PNG that you have doesn't match any of the ones on the page that you linked

**Comment by ezrichards** [comment]
> Are you sure? The PNG that you have doesn't match any of the ones on the page that you linked

Yes. I was sent a custom one (maybe it's new?) - I will forward the email to you.

**Pull request merged**
