### PR TITLE
admin/volunteer login: redirect to existing page

### PR DESCRIPTION
**Pull request by ezrichards**
Okay, so the bytes of text (rather stupidly) bother me when logging in. I think we can just redirect to our pages for teachers which would be kind of nice. All of the text doesn't necessarily apply but it may not matter or we can add a boolean flag for this.

### CODE REVIEW

**Comment by sumnerevans** [comment]
I don't want to merge this, as it will be confusing to redirect to a page that doesn't apply. Remember that the audience here is not just us, it's other volunteers and professors, and badly formatted text is better than wrong text.

**Comment by ezrichards** [comment]
Fixed, I think.

**Review by sumnerevans — APPROVED** [review]
Haven't tested, but this probably won't break anything too badly.

**Review by sumnerevans — APPROVED** [review]
Haven't tested, but this probably won't break anything too badly.

**Pull request merged**
